version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:18080"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - server
    command: ["python", "-u", "rpc_client.py"]
    restart: "no"
